Add filter to loadAppsInChat to exclude apps without a bot
plasne/microsoft-graph-toolkit pull request #73
Opened 2024-02-22 21:30 UTC by andrewDoing

Task 493
Tested in ChatList that loading a Bot chat calls the API with a filter now

### PR Type

### Description of the changes

### PR checklist
- [ ] Project builds (`yarn build`) and changes have been tested in at least two supported browsers (Edge + non-Chromium based browser)
- [ ] All public APIs (classes, methods, etc) have been documented following the jsdoc syntax
- [ ] [Stories](https://github.com/microsoftgraph/microsoft-graph-toolkit/wiki/Storybook#writing-stories) have been added and existing stories have been tested
- [ ] Added appropriate [documentation](https://github.com/microsoftgraph/microsoft-graph-toolkit/wiki/Documentation). Docs PR: 

- [ ] License header has been added to all new source files (`yarn setLicense`)
- [ ] Contains **NO** breaking changes

### Other information

2024-02-22 21:32 UTC, TechnicallyWilliams approved these changes

2024-02-23 15:11 UTC, plasne commented on packages/mgt-chat/src/statefulClient/graph.chat.ts
>  export const loadAppsInChat = async (graph: IGraph, chatId: string): Promise<AppCollection> => {
Should be called loadBotsInChat now since it doesn't include apps.

2024-02-23 15:11 UTC, plasne requested changes
Need to change name. Maybe there is even an opportunity to reduce filtering code where this is used.

2024-02-23 15:12 UTC, plasne commented
There are quite a few places that refer to this as "apps" whereas it is now "bots".

2024-02-23 21:09 UTC, plasne approved these changes
And now all this might change with Gavin's PR on bots: https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/3071

2024-02-26 14:37 UTC, plasne approved these changes

2024-02-26 17:09 UTC, merged